model:
    arch: segnet
data:
    dataset: camvid
    train_split: train
    val_split: val
    img_rows: 360
    img_cols: 480
    path: /media/max/DATA/camvid
training:
    train_iters: 30
    batch_size: 4
    val_interval: 1000
    n_workers: 8
    print_interval: 10
    optimizer:
        name: 'adam'
        lr: 1.0e-3
        weight_decay: 0.0005
        momentum: [0.9,0.999]
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
    resume: null
